apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name:  {{ template "name" . }}
          image: {{.Values.DOCKER_REGISTRY}}/{{.Values.image.name}}:{{.Values.image.tag}}
          ports:
            - containerPort: {{.Values.service.port}}
          readinessProbe:
            httpGet:
              path: /
              port: {{.Values.service.port}}
            initialDelaySeconds: 0
            periodSeconds: 1