FROM golang:1.13-alpine as builder
WORKDIR /workspace
COPY / /workspace/
RUN go build -o app


FROM alpine as runtime
EXPOSE 8081
ENTRYPOINT ["app"]
COPY --from=builder /workspace/app /usr/local/bin/
