image:
  name: s4/envlibs
  tag: ${GIT_COMMIT}

DOCKER_REGISTRY: ${DOCKER_REGISTRY}

service:
  port: 8081

ingress:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi
